services:

  # Prometheus collects and stores application metrics
  prometheus:

    # Use the official Prometheus Docker image
    image: prom/prometheus:latest

    # Give the monitoring container a clear name
    container_name: sit223-prometheus

    # Prometheus web dashboard will be available on localhost:9090
    ports:
      - "9090:9090"

    # Mount our Prometheus configuration into the container
    # Read-only (:ro) prevents the container from changing our config file
    volumes:
         # Prometheus configuration
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        # Backend alert rules
      - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
  
    

    # Restart Prometheus automatically if it unexpectedly stops
    restart: unless-stopped

   # Grafana provides a visual dashboard for Prometheus metrics
  grafana:

    # Use the official Grafana Docker image
    image: grafana/grafana:latest

    # Give the dashboard container a clear name
    container_name: sit223-grafana

    # Grafana web interface will be available on localhost:3000
    ports:
      - "3000:3000"

    # Keep Grafana running if it unexpectedly stops
    restart: unless-stopped

    # Start Grafana after Prometheus has been started
    depends_on:
      - prometheus 
    # Alertmanager receives alerts generated by Prometheus
  alertmanager:

    # Use the official Prometheus Alertmanager image
    image: prom/alertmanager:latest

    # Give the container a clear name
    container_name: sit223-alertmanager

    # Alertmanager web interface
    ports:
      - "9093:9093"

    # Load our Alertmanager configuration file
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro

    # Tell Alertmanager which configuration file to use
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"

    # Restart automatically unless stopped manually
    restart: unless-stopped